export let service = [
  {
    id: "1",
    name: "Career services",
    building: "Student Services Center",
    room: "230",
    ou: "cars",
  },
  {
    id: "2",
    name: "Conference services",
    building: "Shepherd Union",
    room: "301",
    ou: "cons",
  },
  {
    id: "3",
    name: "Counseling services",
    building: "Student Services Center",
    room: "280",
    ou: "cps",
  },
  {
    id: "4",
    name: "Dean of students",
    building: "Miller Admin Building",
    room: "317",
    ou: "dean",
  },
  {
    id: "5",
    name: "Dining services",
    building: "Shepherd Union",
    room: "303",
    ou: "dining",
  },
  {
    id: "6",
    name: "Housing services",
    building: "Wildcat Village",
    room: "Multiple",
    ou: "hse",
  },
  {
    id: "7",
    name: "International students",
    building: "Shepherd Union",
    room: "143",
    ou: "iss",
  },
  {
    id: "8",
    name: "Non-Trad Center",
    building: "Shepherd Union",
    room: "322",
    ou: "non-trad",
  },
  {
    id: "9",
    name: "Campus recreation",
    building: "Wildcat center",
    room: "101",
    ou: "rec",
  },
  {
    id: "10",
    name: "Student Involvment",
    building: "Shepherd Union",
    room: "326",
    ou: "sac",
  },
  {
    id: "11",
    name: "Union/info desk",
    building: "Shepherd Union",
    room: "N/A",
    ou: "slife",
  },
  {
    id: "12",
    name: "Student Support Services SSS",
    building: "Student Services Center",
    room: "266",
    ou: "sss",
  },
  {
    id: "13",
    name: "SA VP office",
    building: "Miller Administration",
    room: "N/A",
    ou: "ssvp",
  },
  {
    id: "14",
    name: "Disability services",
    building: "Student Services Center",
    room: "181",
    ou: "swd",
  },
  {
    id: "15",
    name: "Womens Center",
    building: "Shepherd Union",
    room: "323",
    ou: "sws",
  },
  {
    id: "16",
    name: "Testing centers",
    building: "Multiple",
    room: "Multiple",
    ou: "tc",
  },
  {
    id: "17",
    name: "Upward Bound",
    building: "Annex 3",
    room: "All",
    ou: "ub",
  },
  {
    id: "18",
    name: "Veterans Services",
    building: "Shepherd Union",
    room: "322",
    ou: "vet",
  },
  {
    id: "19",
    name: "Veterans Upward Bound",
    building: "Annex 12",
    room: "All",
    ou: "vub",
  },
  {
    id: "20",
    name: "Outdoor Programs",
    building: "Outdoor Programs Building",
    room: "All",
    ou: "rec",
  },
  {
    id: "21",
    name: "Wildcat Center",
    building: "Wildcat Center",
    room: "All",
    ou: "wi",
  },
  {
    id: "22",
    name: "University village housing",
    building: "University Village",
    room: "101",
    ou: "hse",
  },
  {
    id: "23",
    name: "University village lab",
    building: "University Village",
    room: "108",
    ou: "UV-open-lab",
  },
  {
    id: "24",
    name: "Wattis lab",
    building: "Wattis",
    room: "118",
    ou: "WattisOpenLab",
  },
  {
    id: "25",
    name: "CCEL",
    building: "Shepherd Union",
    room: "324",
    ou: "CCEL",
  },
  {
    id: "26",
    name: "Equity & Diversity",
    building: "Student services center",
    room: "150",
    ou: "mcc",
  },
  {
    id: "27",
    name: "Writing center",
    building: "Elizabeth Hall",
    room: "210",
    ou: "writingcenter",
  },
  {
    id: "28",
    name: "Library south lab",
    building: "Stewart Library",
    room: "Foor 2",
    ou: "librarysouthside",
  },
  {
    id: "29",
    name: "Library north lab",
    building: "Stewart Library",
    room: "Floor 2",
    ou: "librarynorthside",
  },
  {
    id: "30",
    name: "Elizabeth Hall lab",
    building: "Elizabeth Hall",
    room: "213",
    ou: "EHOpenLab",
  },
  {
    id: "31",
    name: "Tracy Hall lab",
    building: "Tracy Hall",
    room: "101",
    ou: "TYOpenLab",
  },
  {
    id: "32",
    name: "Union Lab",
    building: "Shepherd Union",
    room: "230",
    ou: "UnionOpenLab",
  },
  {
    id: "33",
    name: "Union Classroom",
    building: "Shepherd Union",
    room: "230C",
    ou: "UnionOpenLabClassroom",
  },
]
